spring.application.name=my-messenger
app.jwt.secret=${JWT_SECRET:bXktbWVzc2VuZ2VyLWRldi1qd3Qtc2VjcmV0LWtleS0zMi1ieXRlcw==}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:900000}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:2592000000}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.datasource.url=jdbc:mysql://localhost:3307/my-messenger
spring.datasource.username=avas
spring.datasource.password=avas_local
spring.data.mongodb.uri=mongodb://avas:1860b81c60f134d81a55ffc6c7ec97a4@localhost:27017/my-messenger?authSource=admin
spring.jpa.hibernate.ddl-auto=validate

# Enable Flyway (scripts will live in src/main/resources/db/migration)
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration