ALTER TABLE conversions
    ADD COLUMN user_id BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN client_id BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN is_pin BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN is_archive BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN deleted_at DATETIME(6) NULL,
    ADD COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

ALTER TABLE messages
    ADD COLUMN user_id BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN parent_message_id BIGINT NULL,
    ADD COLUMN content VARCHAR(1000) NULL,
    ADD COLUMN message_type VARCHAR(20) NULL;

ALTER TABLE `groups`
    ADD COLUMN name VARCHAR(256) NOT NULL DEFAULT '',
    ADD COLUMN `desc` VARCHAR(1024) NOT NULL DEFAULT '',
    ADD COLUMN member_count INT NULL,
    ADD COLUMN deleted_at DATETIME(6) NULL,
    ADD COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

ALTER TABLE group_members
    ADD COLUMN user_id BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN group_id BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN role VARCHAR(50) NOT NULL DEFAULT 'MEMBER',
    ADD COLUMN deleted_at DATETIME(6) NULL,
    ADD COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);